version: '3.8'

services:
  discord-bot:
    build:
      context: .
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - discord-web-api
    restart: always

  discord-web-api:
    build:
      context: /Users/james/Documents/Projects/discord-web-api
    env_file:
      - .env
    ports:
      - "5001:5000"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
